framework:
#IcI je passse en FR les different erreur exemple mdp qui correspond pas
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:
